### ISSUE TITLE
Reading DAOSTORM files

### ISSUE THREAD

**Issue by Ejdrup** [flevet/Coloc-Tesseler#1]
Hi,
I'm working with DAOSTORM rather than ThunderSTORM, but your tool only seems to accept .csv, rather than the .txt or .hd5f provided by DAOSTORM. Any chance for an implementation of this, or do you know of any pre-built converter tool?

**Comment by flevet** [comment]
Hi,

I have never used a DAOSTORM file but if the txt file it provides is comma separated and have a similar header as the one of Thunderstorm, you can changed the file extension from txt to csv and it should work.
