### ISSUE TITLE
Function of 'On ROIs' 

### ISSUE THREAD

**Issue by GayatriChandran** [flevet/Coloc-Tesseler#2]
With reference to the Coloc-Tesseler GUI, what is the function of the 'On ROIs' option in the 'colocalization' tab ? Is it recommended to leave it enabled or disabled ?

**Comment by flevet** [comment]
When checked, it applies the coefficients only inside these ROIs, i.e. for each ROI, the computation is limited to the localizations inside the ROI. No recommandation here: it depends on the organization of the localization. If there is a big difference in the loc organization of the ROI wrt to the other region, it may be interesting to use ROIs.
